name: Publish Extension

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VSCE_PAT: ${{ secrets.VSCE_PAT }}
  OVSX_PAT: ${{ secrets.OVSX_PAT }}

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Gives permission to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.7.0
          run_install: false
          
      - name: Get package info
        id: package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build extension
        run: pnpm run build
        
      - name: Package VSIX
        run: pnpm run package:vsce
        
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.package.outputs.name }}-${{ steps.package.outputs.version }}.vsix
          body: |
            Release ${{ github.ref_name }} of the AI Memory extension.
            
            ## How to install
            
            ### From VSIX file
            1. Download the `.vsix` file from this release
            2. In Cursor, open the Command Palette (Ctrl+Shift+P / Cmd+Shift+P)
            3. Run "Extensions: Install from VSIX..." and select the downloaded file
            
            ### From Cursor Extension Panel
            This version will be available in the Cursor Extension Panel soon.
      
      - name: Publish to VSCode Marketplace
        if: env.VSCE_PAT != ''
        run: |
          npm install -g @vscode/vsce
          vsce publish -p "$VSCE_PAT"
      
      - name: Publish to Open VSX Registry
        if: env.OVSX_PAT != ''
        run: |
          npm install -g ovsx
          ovsx publish -p "$OVSX_PAT"
          
      - name: Log release URL
        run: echo "Released at ${{ steps.create_release.outputs.url }}" 